### ISSUE TITLE
Is there any CashCode Emulator for testing?

### ISSUE THREAD

**Issue by ShGKme** [Desionlab/node-cashcode-bv#10]
Hello!

Is there a way to develop (and test) for CashCode BV without direct physical access to BV?  
Maybe an emulator, virtual cashcode or anything else...

Sorry for question not directly about this repo. Remote working...

**Comment by fenixphp** [comment]
Hello.
The freely available tools such I did not find.
For myself, I bought used device.

**Comment by ShGKme** [comment]
Thanks @fenixphp! Sounds sad, maybe I'll try to make some.
