### ISSUE TITLE
Error: Request timeout.

### ISSUE THREAD

**Issue by yabafinet** [Desionlab/node-cashcode-bv#4]
Hi, I am receiving this error and the cashcode is connected to the COM2 port.

This is the complete error:
`Error: Request timeout.
    at Timeout.timerHandler (C:\Users\MIDASRED-AUTOSERV\Documents\node-cashcode-bv\Source\CCNet\BillValidator.js:711:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

What could be happening ?

**Comment by fenixphp** [comment]
You use an example from the library if there is not then give the code as you try to use the library.
Also you can see #3

**Comment by yabafinet** [comment]
Hi, I'm using the one in the library, this example:
Examples\CCNet\bv-full.js

**Comment by fenixphp** [comment]
At what stage is this happening? 

1) Need the whole log.
2) Which model validator you use?

**Comment by yabafinet** [comment]
The model is: **MSM-3024**

Only this error returns to me:
`Error: Request timeout. at Timeout.timerHandler (node-cashcode-bv \ Source \ CCNet \ BillValidator.js: 711: 16) at ontimeout (timers.js: 498: 11) at tryOnTimeout (timers. js: 323: 5) at Timer.listOnTimeout (timers.js: 290: 5)`

**Comment by fenixphp** [comment]
Maybe you firmware in PULSE mode, but you need CCNet.

**Comment by yabafinet** [comment]
@fenixphp 
How can I know if it is in PULSE mode?

**Comment by fenixphp** [comment]
Add to the file "CCNetParser.js" after line 47and before 58:
``` javascript
    /*  */
    if (this.packet.length == this.packetLength) {
      console.log(this.packet);
      /*  */
      this.push(this.packet);
      
      /*  */
      this.packet = new Buffer(0);
      
      /*  */
      this.packetLength = 0;
    }
```
And check the incoming packets. If they are not there at all, then your device is in pulse mode.

**Comment by yabafinet** [comment]
@fenixphp 
Apparently he is not in PULSE mode, but he keeps returning timeout.

This is part of what I return:
<Buffer 02 03 06 30 41 b3>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
on: status 33
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
Error: Request timeout.
     at Timeout.timerHandler (C: \ Users \ MIDASRED-AUTOSERV \ Documents \ node-cashcode-bv \ Source \ CCNet \ BillValidator.js: 711: 16)
     at ontimeout (timers.js: 498: 11)
     at tryOnTimeout (timers.js: 323: 5)
     at Timer.listOnTimeout (timers.js: 290: 5)
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 33 da 81>

**Comment by fenixphp** [comment]
The fact is that in return you receive mirrored data (also what you send), but it should not be so. Here is an example of the correct response from a device:
```
<Buffer 02 03 06 00 c2 82>
<Buffer 02 03 06 13 d8 a0>
on:initialize
<Buffer 02 03 27 53 4d 2d 52 55 31 33 38 30 41 46 20 20 20 20 30 30 4b 36 31 36 30 38 32 35 33 38 27 f3 18 54 8f cb 06 63 e7>
<Buffer 02 03 7d 00 00 00 00 00 00 00 00 00 00 01 52 55 53 01 05 52 55 53 01 01 52 55 53 02 05 52 55 53 02 01 52 55 53 03 05 52 55 53 03 01 52 55 53 00 02 52 ... >
{ model: 'SM-RU1380AF',
  serial: '00K616082XXX',
  asset: '27f318548fcXXX' }
[ { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 10, code: 'RUS', enabled: false, security: false },
  { amount: 50, code: 'RUS', enabled: false, security: false },
  { amount: 100, code: 'RUS', enabled: false, security: false },
  { amount: 500, code: 'RUS', enabled: false, security: false },
  { amount: 1000, code: 'RUS', enabled: false, security: false },
  { amount: 5000, code: 'RUS', enabled: false, security: false },
  { amount: 1, code: 'RUS', enabled: false, security: false },
  { amount: 2, code: 'RUS', enabled: false, security: false },
  { amount: 5, code: 'RUS', enabled: false, security: false },
  { amount: 10, code: 'RUS', enabled: false, security: false },
  { amount: 200, code: 'RUS', enabled: false, security: false },
  { amount: 2000, code: 'RUS', enabled: false, security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 0,
    code: '\u0000\u0000\u0000',
    enabled: false,
    security: false },
  { amount: 1, code: 'BAR', enabled: false, security: false } ]
<Buffer 02 03 06 00 c2 82>
Ok.
```

The reason for this behavior should be found in the documentation from your device or you have a comport that sends all the requests back.

**Comment by sarathjasrin** [comment]
I also get a timeout error. When this is happening 

- At the start, it's not giving any error when I'm trying to call `device.close()` function it's gives timeout error. 

- When we having one or more transactions after the `close` or `end` function. The next time calling `device.begin()`. It's giving error.

- Also if try checking whether the cash reader is online. after `device.close()`. It's giving timeout. 

How I can handle this. Thanks

**Comment by fenixphp** [comment]
@sarathjasrin 
If your problem is the same as described above, then without access to a specific device, I can not help you.

**Comment by sarathjasrin** [comment]
When calling `device.close()` method it's gives `TypeError: this.onSerialPortClose is not a function`

> @sarathjasrin
> If your problem is the same as described above, then without access to a specific device, I can not help you.

BillValidator : `Cashcode MSM 3021`
